try {
    throw RuntimeError("test")
} catch (e) {
    x = "caught"
}